name: Playwright Java CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- BUILD DOCKER ----------
      - name: Build Docker Image
        run: docker build -t playwright-tests .

      # ---------- RUN TESTS IN DOCKER ----------
      - name: Run Tests in Docker
        run: |
          docker run \
            -v ${{ github.workspace }}/target:/app/target \
            playwright-tests

      # ---------- SETUP JAVA FOR REPORT ----------
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # ---------- GENERATE ALLURE REPORT ----------
      - name: Generate Allure Report
        run: mvn allure:report

      # ---------- DEPLOY TO GITHUB PAGES ----------
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
