name: Playwright Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    name: Run Tests (${{ matrix.browser }})
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.42.0-jammy


    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]


    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t playwright-tests .

      - name: Run Tests in Docker
        run: docker run playwright-tests

      # ---------- SETUP JAVA FOR REPORT ----------
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install Playwright Browsers
        run: |
          mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Tests
        run: mvn clean test -Dbrowser=${{ matrix.browser }} -Dheadless=true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: target/allure-results

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-${{ matrix.browser }}
          path: target/surefire-reports

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: allure-results-temp

      - name: Merge Allure Results
        run: |
          mkdir -p target/allure-results
          cp -r allure-results-temp/**/allure-results/* target/allure-results || true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
          force_orphan: true